# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S_RFiAYfXh20uytizTDAGLpchkovIrU1
"""

import os
import json
import requests
from dotenv import load_dotenv

load_dotenv()

# Obtener credenciales
SHOP_DOMAIN = os.getenv('SHOPIFY_SHOP_DOMAIN')
ACCESS_TOKEN = os.getenv('SHOPIFY_ACCESS_TOKEN')

print(f"Conectando a: {SHOP_DOMAIN}")

# URL de la API
url = f"https://{SHOP_DOMAIN}/admin/api/2024-01/products.json"
headers = {
    'X-Shopify-Access-Token': ACCESS_TOKEN,
    'Content-Type': 'application/json'
}

# Obtener productos
response = requests.get(url, headers=headers, params={'limit': 250})

if response.status_code == 200:
    data = response.json()
    products = data.get('products', [])
    print(f"Productos obtenidos: {len(products)}")

    # Guardar en archivo
    with open('shopify_products.json', 'w', encoding='utf-8') as f:
        json.dump(products, f, indent=2, ensure_ascii=False)

    print("✅ Datos guardados en shopify_products.json")
else:
    print(f"❌ Error: {response.status_code}")
    print(response.text)